name: Update Google Sheets

on:
  schedule:
    - cron: '8 13 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run updater
        env:
          GSHEETS_KEY: ${{ secrets.GSHEETS_KEY }}
          SPREAD_ID:   ${{ secrets.SPREAD_ID }}
        run: |
          python update_news.py
